export const teamDetailData = [
    {
        team_id: "1",
        logo: "/empty_img_circle.png",
        name: "Team A",
        gugun: "중구",
        sido: "서울특별시",
        lose_count: 2,
        mmr: 2200,
        point: 2000,
        win_count: 5,
        winning_streak: 2,
        description: "Team A의 설명입니다.",
        member_count: 7,
        mojib: 0,
        },
        {
        team_id: "2",
        logo: "/google_logo.png",
        name: "팀 구글",
        gugun: "남구",
        sido: "부산광역시",
        lose_count: 1,
        mmr: 2100,
        point: 2500,
        win_count: 3,
        winning_streak: 3,
        description: "Team B의 설명입니다.",
        member_count: 8,
        mojib: 1,
        },
        {
        team_id: "3",
        logo: "/kakao_logo.png",
        name: "팀 카카오",
        gugun: "서구",
        sido: "대전광역시",
        lose_count: 3,
        mmr: 2000,
        point: 1500,
        win_count: 4,
        winning_streak: 1,
        description: "Team C의 설명입니다.",
        member_count: 6,
        mojib: 0,
        },
        ];
  